### ISSUE TITLE
私有云的配置会有报错，请问是什么问题呢

### ISSUE THREAD

**Issue by web0428** [rongcloud/rongcloud-imkit-flutter-sdk#3]

**Comment by web0428** [comment]
{"ptid":"30565-14973","code":30007,"data":"<errors><code>403</code><url>/navi.xml</url><errorMessage>AppIdisnotexist.</errorMessage></errors>"

**Comment by loginSin** [comment]
可能是私有云 im 服务 appkey 和 端上的 appkey不一致

**Comment by web0428** [comment]
我们是本地化的,服务端地址的配置也是正确的，appkey也是正确的，可以麻烦帮我看一下原因吗

**Comment by arielyang** [comment]
私有云的客户请通过销售和客服联系
